# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
      with:
        submodules: true
    #- name: Init submodules
    #  run: git submodule update --init --recursive
    - name: Install libssl-dev
      run: sudo apt-get install libssl-dev
    - name: "[Release g++] Build & Test"
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ github.workspace }}/build
        source-dir: ${{ github.workspace }}
        cc: gcc
        cxx: g++
        build-type: Release
        run-test: true
        ctest-options: -V
